### ISSUE TITLE
Error on serial event

### ISSUE THREAD

**Issue by paolon** [kitschpatrol/BrainGrapher#6]
Hi!
I tried the sketch with a Mindwave Mobile 2 on both Mac and PC with Processing 3.5.4. The application always crashes after 4 packets received.
This is part of the console log:

`Received string over serial: ���A���?���$Y���$Y���%X���%X���%X���%X���%X���%X` [omissis]
`Received string over serial: r���z���Ӫ����ͪ��ը���l���a���񌪪��Ū���Ԫ���Ī��`
`Received string over serial: s���z����􊪪��듪���򌪪�������x���	t���|���������`[omissis]
`Received string over serial: s���"[���2K���8E���3J���,Q���&W���!\��� ]���!\`[omissis]
`Received string over serial: s���j���!\���3J���<A���2K��� ]���h���j`[omissis]
`Received string over serial: -�����Y7[$�%�+a����#Z���8E���E8���G6���D9`[omissis]
`Received string over serial: s���
p���
p���l���f���%X���2K���:C���5H`[omissis]
`Error, disabling serialEvent() for /dev/tty.MindWaveMobile-SerialPo
null`

Are the strings I receive correct? Why does an error always come after the first packets?
Thank you in advance for the suggestions you can give me.

**Comment by tziporaziegler** [comment]
@paolon Just ran into the same issue. Did you ever figure this out?

**Comment by kitschpatrol** [comment]
Sorry for the delay. This library is not directly compatible with the Mindwave Mobile 2, it's intended for use with data provided by the [Arduino Brain Library](https://github.com/kitschpatrol/brain).

Compatibility with additional protocols is not inconceivable, but would require documentation of the protocol and an additional code path in the serial-handling code. Open to PRs, but closing this issue as unsupported.
